In [9]:
import numpy as np

def sig(x) :
    result = 1 / (1+np.exp(-x))
    return result

def activate (x, w, a) :
    x1 = np.matmul(w, x) + a
    x2 = sig(x1)

In [15]:
x = 0.87, 0.97, 0.97, 0.98
w1 = np.array([
    [-4.302, -5.578, -2.296, -1.294],
    [ 0.233, -3.465, -0.199, -1.105],
    [ 0.606,  1.316,  0.317,  0.494],
    [ 0.458, 0.873, 0.315, 0.806],
    [-1.439, -2.01, 2.421, -1.977],
])
a1 = [10.799, 3.502, 1.372, 0.705, 0.973]

w2 = np.array([
    [-9.241, -3.807, 2.043, 2.45, -1.698],
    [9.368, 3.75, -2.172, -2.487, 2.476]
])

a2 = [1.401, -1.447]

In [16]:
result1 = activate(x, w1, a1)
result1

array([0.13591517, 0.28246441, 0.98142793, 0.95459652, 0.13970768])

In [17]:
activate(result1, w2,a2)

array([0.9599311 , 0.03646233])

In [18]:
import numpy as np
import pandas as pd

def sig(x) :
    result = 1 / (1+np.exp(-x))
    return result

def activate2 (x,w,a) :
    x1 = np.matmul(w,x) + a
    x2 = sig(x1)
    return x1, x2

In [19]:
gob_hab1, ugyu1 = activate2(x, w1, a1)
gob_hab2, ugyu2 = activate2(ugyu1, w2, a2)

In [20]:
gob_hab1, ugyu1

(array([-1.84964, -0.93227,  3.96735,  3.0457 , -1.81772]),
 array([0.13591517, 0.28246441, 0.98142793, 0.95459652, 0.13970768]))

In [21]:
gob_hab2, ugyu2

(array([ 3.17626101, -3.27433196]), array([0.9599311 , 0.03646233]))